### ISSUE TITLE
Blank page when I navigate to localhost

### ISSUE THREAD

**Issue by samcromer** [UltimateAngular/angular-fundamentals-seed#11]
I have everything installed and built, zero errors but when I do yarn start and browse to localhost:4000 all i see is a blank page.

**Comment by samcromer** [comment]
Here is my log file:

VM34:6 Error executing AG js: ReferenceError: e is not defined
(anonymous) @ VM34:6
dev-server.js:49 [HMR] Waiting for update signal from WDS...
bootstrap 24e60464162d6c13b695:708 Uncaught Error: Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.0
    at module.exports (C:\Users\Sam.Cromer.2017011SC\Documents\Web\angular-fundamentals-seed-master\angular-fundamentals-seed-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\Sam.Cromer.2017011SC\Documents\Web\angular-fundamentals-seed-master\angular-fundamentals-seed-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Users\Sam.Cromer.2017011SC\Documents\Web\angular-fundamentals-seed-master\angular-fundamentals-seed-master\node_modules\sass-loader\index.js:4:12)
    at module.exports (C:\Users\Sam.Cromer.2017011SC\Documents\Web\angular-fundamentals-seed-master\angular-fundamentals-seed-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\Sam.Cromer.2017011SC\Documents\Web\angular-fundamentals-seed-master\angular-fundamentals-seed-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Users\Sam.Cromer.2017011SC\Documents\Web\angular-fundamentals-seed-master\angular-fundamentals-seed-master\node_modules\sass-loader\index.js:4:12)
    at Object../app/app.component.scss (http://localhost:4000/build/app.js:717:7) [<root>]
    at __webpack_require__ (http://localhost:4000/build/app.js:660:30) [<root>]
    at fn (http://localhost:4000/build/app.js:84:20) [<root>]
    at Object../app/app.component.ts (http://localhost:4000/build/app.js:735:18) [<root>]
    at __webpack_require__ (http://localhost:4000/build/app.js:660:30) [<root>]
    at fn (http://localhost:4000/build/app.js:84:20) [<root>]
    at Object../app/app.module.ts (http://localhost:4000/build/app.js:752:23) [<root>]
    at __webpack_require__ (http://localhost:4000/build/app.js:660:30) [<root>]
    at fn (http://localhost:4000/build/app.js:84:20) [<root>]
    at Object../main.ts (http://localhost:4000/build/app.js:783:74) [<root>]
    at __webpack_require__ (http://localhost:4000/build/app.js:660:30) [<root>]
    at fn (http://localhost:4000/build/app.js:84:20) [<root>]
    at Object.7 (http://localhost:4000/build/app.js:10047:18) [<root>]
    at __webpack_require__ (http://localhost:4000/build/app.js:660:30) [<root>]
:4000/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
client?59d4:38 [WDS] Hot Module Replacement enabled.
client?59d4:38 [WDS] Errors while compiling. Reload prevented.
client?59d4:101 ./app/app.component.scss
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.0
    at module.exports (C:\Users\Sam.Cromer.2017011SC\Documents\Web\angular-fundamentals-seed-master\angular-fundamentals-seed-master\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\Sam.Cromer.2017011SC\Documents\Web\angular-fundamentals-seed-master\angular-fundamentals-seed-master\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Users\Sam.Cromer.2017011SC\Documents\Web\angular-fundamentals-seed-master\angular-fundamentals-seed-master\node_modules\sass-loader\index.js:4:12)
 @ ./app/app.component.ts 11:17-48
 @ ./app/app.module.ts
 @ ./main.ts
 @ multi app
errors @ client?59d4:101

**Comment by helmutgranda** [comment]
Did you see this error?

> **Uncaught Error: Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (59)
> For more information on which environments are supported please see:
> https://github.com/sass/node-sass/releases/tag/v3.13.0**

**Comment by helmutgranda** [comment]
By the way, I just ran into a similar issue, I figured out it was my version of NODE that I was running 10.0.0. After downgrading to 8.11.1 everything worked out fine. I am not sure if this is the same issue you have but worth a shot.

`node -v`

**Comment by SaMiCoOo** [comment]
Here is my machine settings, `High Sierra v10.13.4 , Darwin x64`.

```
$ node -v
v10.0.0

$ npm -v
5.6.0

$ yarn -v
1.6.0
```

So what I did was simple, just remove the locked dev-dependencies of *node-sass* and *sass-loader* from `package.json` then simply run:

```
yarn add node-sass sass-loader --dev
```

fixed everything for me.

here check my fork of the project, this commit shows the diff in my `package.json`

[dependencies fix](https://github.com/SaMiCoOo/angular-fundamentals-seed/commit/29bd0e6b1842fc492c2353b296e8f98c0b323359)

I hope this fix it for you as well.
