### ISSUE TITLE
 Cannot find module 'chalk'

### ISSUE THREAD

**Issue by rustan-id** [UltimateAngular/angular-fundamentals-seed#3]
$ yarn start
yarn start v0.21.3
$ webpack --config vendor/webpack.config.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gmaimunah/Documents/Ultimate Angular/Angular 2 Fundamental/angular2master/vendor/webpack.config.js:5:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.

**Comment by rustan-id** [comment]
$ sudo npm install chalk
└─┬ chalk@1.1.3 
  ├── ansi-styles@2.2.1 
  ├── escape-string-regexp@1.0.5 
  ├── has-ansi@2.0.0 
  └── supports-color@2.0.0 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

$ yarn start
yarn start v0.21.3
$ webpack --config vendor/webpack.config.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'progress-bar-webpack-plugin'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gmaimunah/Documents/Ultimate Angular/Angular 2 Fundamental/angular2master/vendor/webpack.config.js:6:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.

]$ sudo npm install progress-bar-webpack-plugin
angular-fundamentals-seed@0.1.0 /home/gmaimunah/Documents/Ultimate Angular/Angular 2 Fundamental/angular2master
└─┬ progress-bar-webpack-plugin@1.9.0 
  ├─┬ object.assign@4.0.4 
  │ ├─┬ define-properties@1.1.2 
  │ │ └── foreach@2.0.5 
  │ ├── function-bind@1.1.0 
  │ └── object-keys@1.0.11 
  └── progress@1.1.8 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[gmaimunah@ghina-id angular2master]$ yarn start
yarn start v0.21.3
$ webpack --config vendor/webpack.config.js
build [====================] 100% 0.2 seconds 

Build completed in 0.169s

   [0] dll vendor 12 bytes {0} [built]
error Command failed with exit code 2.

**Comment by rustan-id** [comment]
it's done when i tried in vs code toggle terminal.. Thanks...
